=== chandansh/chandan-practice/ChandanSandBox/liferay practice/liferay_workspace/liferay-plugins-sdk-6.1.0-ce-ga1/portlets/amp-xml-portlet/docroot/WEB-INF/classes/com/test/recipe.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="recipe">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="RecipeIdentifier" />
				<xs:element ref="NameText" />
				<xs:element ref="Description" />
				<xs:element ref="IngredientList" maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="IngredientList">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Ingredient" maxOccurs="unbounded"
					minOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="Ingredient">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="DataCenter" maxOccurs="unbounded"
					minOccurs="0" />
				<xs:element ref="PtimesListQ" maxOccurs="unbounded"
					minOccurs="0" />
				<xs:element ref="PtimesQ" maxOccurs="unbounded"
					minOccurs="0" />
				<xs:element ref="OptionList" maxOccurs="unbounded"
					minOccurs="0" />
				<xs:element ref="PtimesSumQ" maxOccurs="unbounded"
					minOccurs="0" />
				<xs:element ref="TableTimesQ" maxOccurs="unbounded"
					minOccurs="0" />
				<xs:element ref="TableTimesSumQ" maxOccurs="unbounded"
					minOccurs="0" />
				<xs:element ref="CheckBox" maxOccurs="unbounded"
					minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="Quantity">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:integer">
					<xs:attribute name="min" type="xs:integer" use="optional" />
					<xs:attribute name="max" type="xs:integer" use="optional" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="Corestructure">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="SKU" />
				<xs:element ref="Quantity" />
				<xs:element ref="Price" />
				<xs:element ref="DateTimeCreate" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="SKU" type="xs:string" />
	<xs:element name="RecipeIdentifier" type="xs:string" />

	<xs:element name="PtimesQ">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Corestructure" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="OptionList">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Corestructure" maxOccurs="unbounded" />
				<xs:element ref="OptionValue" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="PtimesListQ">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="HeaderText" />
				<xs:element ref="Corestructure" maxOccurs="unbounded" />
				<xs:element ref="PtimesQ" minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="PtimesSumQ">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="HeaderText" />
				<xs:element ref="Corestructure" maxOccurs="unbounded" />
				<xs:element ref="QuantityType" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="TableTimesQ">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="SKU" />
				<xs:sequence minOccurs="0">
					<xs:element ref="Quantity" />
					<xs:element ref="Price" />
					<xs:element ref="DateTimeCreate" />
				</xs:sequence>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="TableTimesSumQ">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="HeaderText" />
				<xs:element ref="Corestructure" maxOccurs="unbounded" />
				<xs:element ref="QuantityType" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="PTableQ">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="HeaderText" />
				<xs:element ref="Corestructure" maxOccurs="unbounded" />
				<xs:element ref="QuantityType" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="QuantityType">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="LabelText" />
				<xs:element ref="Quantity" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="CheckBox">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Corestructure" maxOccurs="unbounded" />
				<xs:element ref="OptionBox" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="OptionBox">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="LabelText" />
				<xs:element ref="OptionValue" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Price" type="xs:decimal" />
	<xs:element name="NameText" type="xs:string" />
	<xs:element name="HeaderText" type="xs:string" />
	<xs:element name="LabelText" type="xs:string" />
	<xs:element name="Description" type="xs:string" />
	<xs:element name="DateTimeCreate" type="xs:date" />
	<xs:element name="OptionValue" type="xs:string" />
	<xs:element name="DataCenter" type="xs:string" />
</xs:schema>

=== chandansh/chandan-practice/ChandanSandBox/liferay practice/liferay_workspace/liferay-plugins-sdk-6.1.0-ce-ga1/portlets/amp-xml-portlet/docroot/WEB-INF/classes/com/test/recipe.xml
<?xml version="1.0" encoding="UTF-8"?>
<recipe xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="recipe.xsd">
	<RecipeIdentifier>R1</RecipeIdentifier>
	<NameText>Recipe1</NameText>
	<Description>Recipe 1 description</Description>
	<IngredientList>
		<Ingredient>
			<DataCenter>Dallas</DataCenter>
			<PtimesListQ>
				<HeaderText>Select your Server configuration</HeaderText>
				<Corestructure>
					<SKU>01-001-0001</SKU>
					<Quantity>0</Quantity>
					<Price>0.0</Price>
					<DateTimeCreate>2001-01-01</DateTimeCreate>
				</Corestructure>
				<Corestructure>
					<SKU>01-001-0002</SKU>
					<Quantity>0</Quantity>
					<Price>0.0</Price>
					<DateTimeCreate>2001-01-01</DateTimeCreate>
				</Corestructure>
				<Corestructure>
					<SKU>01-001-0003</SKU>
					<Quantity>0</Quantity>
					<Price>0.0</Price>
					<DateTimeCreate>2001-01-01</DateTimeCreate>
				</Corestructure>
				<Corestructure>
					<SKU>01-001-0004</SKU>
					<Quantity>0</Quantity>
					<Price>0.0</Price>
					<DateTimeCreate>2001-01-01</DateTimeCreate>
				</Corestructure>
				<Corestructure>
					<SKU>01-001-0005</SKU>
					<Quantity>0</Quantity>
					<Price>0.0</Price>
					<DateTimeCreate>2001-01-01</DateTimeCreate>
				</Corestructure>
			</PtimesListQ>
			<PtimesListQ>
				<HeaderText>Select your Server configuration</HeaderText>
				<Corestructure>
					<SKU>01-001-0001</SKU>
					<Quantity>0</Quantity>
					<Price>0.0</Price>
					<DateTimeCreate>2001-01-01</DateTimeCreate>
				</Corestructure>
				<Corestructure>
					<SKU>01-001-0002</SKU>
					<Quantity>0</Quantity>
					<Price>0.0</Price>
					<DateTimeCreate>2001-01-01</DateTimeCreate>
				</Corestructure>
				<Corestructure>
					<SKU>01-001-0003</SKU>
					<Quantity>0</Quantity>
					<Price>0.0</Price>
					<DateTimeCreate>2001-01-01</DateTimeCreate>
				</Corestructure>
				<Corestructure>
					<SKU>01-001-0004</SKU>
					<Quantity>0</Quantity>
					<Price>0.0</Price>
					<DateTimeCreate>2001-01-01</DateTimeCreate>
				</Corestructure>
				<Corestructure>
					<SKU>01-001-0005</SKU>
					<Quantity>0</Quantity>
					<Price>0.0</Price>
					<DateTimeCreate>2001-01-01</DateTimeCreate>
				</Corestructure>
			</PtimesListQ>
			<PtimesQ>
				<Corestructure>
					<SKU>01-001-0006</SKU>
					<Quantity>0</Quantity>
					<Price>0.0</Price>
					<DateTimeCreate>2001-01-01</DateTimeCreate>
				</Corestructure>
			</PtimesQ>
			<PtimesQ>
				<Corestructure>
					<SKU>01-001-0007</SKU>
					<Quantity>0</Quantity>
					<Price>0.0</Price>
					<DateTimeCreate>2001-01-01</DateTimeCreate>
				</Corestructure>
			</PtimesQ>
			<OptionList>
				<Corestructure>
					<SKU>01-001-0008</SKU>
					<Quantity>0</Quantity>
					<Price>0.0</Price>
					<DateTimeCreate>2001-01-01</DateTimeCreate>
				</Corestructure>
				<OptionValue>1</OptionValue>
				<OptionValue>2</OptionValue>
				<OptionValue>3</OptionValue>
				<OptionValue>4</OptionValue>
			</OptionList>
			<OptionList>
				<Corestructure>
					<SKU>01-001-0008</SKU>
					<Quantity>0</Quantity>
					<Price>0.0</Price>
					<DateTimeCreate>2001-01-01</DateTimeCreate>
				</Corestructure>
				<OptionValue>1</OptionValue>
				<OptionValue>2</OptionValue>
				<OptionValue>3</OptionValue>
				<OptionValue>4</OptionValue>
			</OptionList>
			
		</Ingredient>
	</IngredientList>
</recipe>
